### ISSUE TITLE
Parcel Example

### ISSUE THREAD

**Issue by YesSeri** [react-bootstrap/code-sandbox-examples#124]
The parcel example doesn't work, at least not for me. 

I get the following message:

Error
Target container is not a DOM element.

[Parcel Example](https://codesandbox.io/s/github/react-bootstrap/code-sandbox-examples/tree/master/parcel)

**Comment by mxschmitt** [comment]
Unfortunately an upstream issue:
- https://github.com/codesandbox/codesandbox-client/issues/2087
- https://github.com/codesandbox/codesandbox-client/issues/1737
- https://github.com/codesandbox/codesandbox-client/issues/4736

**Comment by YesSeri** [comment]
Okay, I don't really need it, just thought I'd let you know.
