### ISSUE TITLE
Basic Example cannot use fragments

### ISSUE THREAD

**Issue by jbakchr** [react-bootstrap/code-sandbox-examples#135]
The basic example doesn't work in the codesandbox when using fragments.

In order for it to work one needs to replace the fragments '<>' with 'div'.

**Comment by nicothin** [comment]
and Basic Example with Sass and custom theming example doesn't work ))

**Comment by mxschmitt** [comment]
Seems like its an upstream issue from the folks at create-react-app: https://github.com/facebook/create-react-app/issues/9877

**Comment by jbakchr** [comment]
Thanks @mxschmitt

**Comment by mxschmitt** [comment]
Seems fixed upstream.
