### ISSUE TITLE
the basic and basic-sass-custom-theming examples don't work for react-bootstrap 2.0.2

### ISSUE THREAD

**Issue by GregLoring** [react-bootstrap/code-sandbox-examples#252]
Simply replace
```
    "bootstrap": "^4.6.0",
    "react-bootstrap": "^1.5.2",
```
with
```
    "bootstrap": "^5.1.3",
    "react-bootstrap": "^2.0.2",
```
in the package.json, and you'll get
```
ModuleNotFoundError
Could not find module in path: 'react-bootstrap/Jumbotron' relative to '/src/App.js'
```
on https://codesandbox.io/.  I got the same message running locally with each node lts from dubnium (v10) thru gallium (v16)

In playing around locally, I received `does not have a default export` from `import foo from 'react-bootstrap'` and `does not export Jumbotron` from `import { Jumbotron } from 'react-bootstrap'`.

**Comment by kyletsang** [comment]
The main readme has been updated with examples for bootstrap 4 and 5.

**Comment by GregLoring** [comment]
And when I opened a ticket on <https://github.com/react-bootstrap/react-bootstrap/issues/> they told me to provide a minimum reproducible example "by using [CodeSandbox](https://codesandbox.io/s/github/react-bootstrap/code-sandbox-examples/tree/master/basic)."  Oh well ...
