### ISSUE TITLE
codesandbox does not work -ModuleNotFoundError: Could not find module in path

### ISSUE THREAD

**Issue by SvenMeyer** [react-bootstrap/code-sandbox-examples#50]
https://codesandbox.io/s/github/0xproject/0x-codesandbox
```
ModuleNotFoundError: Could not find module in path: 'levelup/lib/leveldown' relative to '/node_modules/levelup/lib/levelup.js'
```
![codesandbox - 0x - Screenshot from 2019-12-29 23-24-17](https://user-images.githubusercontent.com/25609/71557000-e80dd080-2a93-11ea-99c2-38bc717c04ac.png)

**Comment by taion** [comment]
This doesn’t look like our code.
